name: Release Drafter

on:
  push:
    branches:
    - main
    - v0.5

jobs:
  draft:
    runs-on: ubuntu-latest
    steps:
      - name: Release Drafter
        if: github.repository == 'Sanuki357/Regalis-s-SCP-CB-Assets-for-Arma-3'
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
